server:
  address: "0.0.0.0"
  port:    3836
  agora_endpoint: http://agora:2826

database:
  filename: data/main.db

logging:
  folder: logs/
  # Values: error, warn, info, http, verbose, debug, silly
  level: info
  console: true

consensus:
  # 2021-01-01:00:00:00 GMT
  genesis_timestamp: 1609459200
